console.log("my name is josiane mushimiyimana");
console.log("hey");
var favoriteFood = 'pizza' ;
var numberOfSlices = 8 ;
console.log(favoriteFood) ;
console.log(numberOfSlices) ;
let changeMe = true ;
changeMe = false ;
console.log(changeMe) ;
const entree = 'Enchiladas' ;
console.log(entree) ;
let levelUp = 10;
levelUp += 5;
let powerLevel = 9001;
powerLevel -= 100;
let multiplyMe = 32;
multiplyMe *= 11;
let quarterMe = 1152;
quarterMe /= 4;